services:
  - type: web
    plan: free
    name: AdvFilter 
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    repo: https://github.com/HKrrish/TestF.git      
    branch: added_UrlShortWithRename_V7.0
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH 
        sync: false
      - key: AUTH_CHANNEL
        sync: false
      - key: DATABASE_NAME 
        sync: false
      - key: DATABASE_URI 
        sync: false 
      - key: LOG_CHANNEL 
        sync: false
      - key: REQ_CHANNEL
        sync: false
      - key: ADMINS
        sync: false 
    autoDeploy: false 
